# Generated by Django 5.0.6 on 2024-06-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_productsdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdb',
            name='Product_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
