# Generated by Django 5.0.6 on 2024-06-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Ct_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Cart Images'),
        ),
    ]
