# Generated by Django 5.0.6 on 2024-06-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_orderdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fd_back_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('fd_back_Mobile', models.IntegerField(blank=True, null=True)),
                ('fd_back_Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('fd_back_Subject', models.CharField(blank=True, max_length=100, null=True)),
                ('fd_back_Message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
