# Generated by Django 5.0.6 on 2024-07-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0005_contactdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
